URL="https://download2287.mediafire.com/gmrmfhcxuxsg/wtyvksczav2yddv/deepin-desktop-community-REPLACE_VERSION-amd64.iso.torrent"
TYPE=torrent
CONTENTS="\
live/filesystem.squashfs|filesystem.squashfs
live/initrd.lz|initrd
live/vmlinuz|vmlinuz"
EXTRACT_INITRD="true"
INITRD_NAME="initrd"
INITRD_TYPE="gz"
