URL="https://kali.download/base-images/kali-REPLACE_VERSION/kali-linux-REPLACE_VERSION-live-amd64.iso.torrent"
TYPE=torrent
CONTENTS="\
live/filesystem.squashfs|filesystem.squashfs
live/initrd.img|initrd
live/vmlinuz|vmlinuz"
EXTRACT_INITRD="true"
INITRD_NAME="initrd"
INITRD_TYPE="zstd"
