URL="http://download.grml.org/grml64-full_REPLACE_VERSION.iso"
TYPE=file
CONTENTS="\
live/grml64-full/grml64-full.squashfs|filesystem.squashfs
boot/grml64full/initrd.img|initrd
boot/grml64full/vmlinuz|vmlinuz"
EXTRACT_INITRD="true"
INITRD_NAME="initrd"
INITRD_TYPE="xz"
